### ISSUE TITLE
docker compose up --build fails because of psycopg2-binary==2.9.6 in requirements.txt

### ISSUE THREAD

**Issue by reuf** [docker/python-docker-dev#6]
Here is a output after running. I'm unsure what to do.

λ docker compose up --build
[+] Building 4.2s (10/11)                                                                                                               docker:default  => [server internal] load build definition from Dockerfile                                                                                       0.0s  => => transferring dockerfile: 1.59kB                                                                                                            0.0s  => [server internal] load .dockerignore                                                                                                          0.0s  => => transferring context: 680B                                                                                                                 0.0s  => [server] resolve image config for docker.io/docker/dockerfile:1                                                                               0.6s  => CACHED [server] docker-image://docker.io/docker/dockerfile:1@sha256:ac85f380a63b13dfcefa89046420e1781752bab202122f8f50032edf31be0021          0.0s  => [server internal] load metadata for docker.io/library/python:3.12.0-slim                                                                      0.5s  => [server base 1/5] FROM docker.io/library/python:3.12.0-slim@sha256:babc0d450bf9ed2b369814bc2f466e53a6ea43f1201f6df4e7988751f755c52c           0.0s  => [server internal] load build context                                                                                                          0.0s  => => transferring context: 288B                                                                                                                 0.0s  => CACHED [server base 2/5] WORKDIR /app                                                                                                         0.0s  => CACHED [server base 3/5] RUN adduser     --disabled-password     --gecos ""     --home "/nonexistent"     --shell "/sbin/nologin"     --no-c  0.0s  => ERROR [server base 4/5] RUN --mount=type=cache,target=/root/.cache/pip     --mount=type=bind,source=requirements.txt,target=requirements.txt  3.0s ------
 > [server base 4/5] RUN --mount=type=cache,target=/root/.cache/pip     --mount=type=bind,source=requirements.txt,target=requirements.txt     python -m pip install -r requirements.txt:
1.642 Collecting blinker==1.6.2 (from -r requirements.txt (line 1))
1.643   Using cached blinker-1.6.2-py3-none-any.whl (13 kB)
1.742 Collecting click==8.1.6 (from -r requirements.txt (line 2))
1.743   Obtaining dependency information for click==8.1.6 from https://files.pythonhosted.org/packages/1a/70/e63223f8116931d365993d4a6b7ef653a4d920b41d03de7c59499962821f/click-8.1.6-py3-none-any.whl.metadata
1.744   Using cached click-8.1.6-py3-none-any.whl.metadata (3.0 kB)
1.801 Collecting colorama==0.4.6 (from -r requirements.txt (line 3))
1.802   Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
1.874 Collecting Flask==2.3.2 (from -r requirements.txt (line 4))
1.875   Using cached Flask-2.3.2-py3-none-any.whl (96 kB)
1.929 Collecting itsdangerous==2.1.2 (from -r requirements.txt (line 5))
1.931   Using cached itsdangerous-2.1.2-py3-none-any.whl (15 kB)
1.993 Collecting Jinja2==3.1.2 (from -r requirements.txt (line 6))
1.994   Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
2.111 Collecting MarkupSafe==2.1.3 (from -r requirements.txt (line 7))
2.112   Obtaining dependency information for MarkupSafe==2.1.3 from https://files.pythonhosted.org/packages/51/94/9a04085114ff2c24f7424dbc890a281d73c5a74ea935dc2e69c66a3bd558/MarkupSafe-2.1.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
2.113   Using cached MarkupSafe-2.1.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.9 kB)
**2.325 Collecting psycopg2-binary==2.9.6 (from -r requirements.txt (line 8))
2.326   Using cached psycopg2-binary-2.9.6.tar.gz (384 kB)**
2.367   Preparing metadata (setup.py): started
2.840   Preparing metadata (setup.py): finished with status 'error'
2.849   error: subprocess-exited-with-error
2.849
2.849   × python setup.py egg_info did not run successfully.
2.849   │ exit code: 1
2.849   ╰─> [34 lines of output]
2.849       /usr/local/lib/python3.12/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
2.849       !!
2.849
2.849               ********************************************************************************
2.849               The license_file parameter is deprecated, use license_files instead.
2.849
2.849               See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
2.849               ********************************************************************************
2.849
2.849       !!
2.849         parsed = self.parsers.get(option_name, lambda x: x)(value)
2.849       running egg_info
2.849       creating /tmp/pip-pip-egg-info-a8tb73r0/psycopg2_binary.egg-info
2.849       writing /tmp/pip-pip-egg-info-a8tb73r0/psycopg2_binary.egg-info/PKG-INFO
2.849       writing dependency_links to /tmp/pip-pip-egg-info-a8tb73r0/psycopg2_binary.egg-info/dependency_links.txt
2.849       writing top-level names to /tmp/pip-pip-egg-info-a8tb73r0/psycopg2_binary.egg-info/top_level.txt
2.849       writing manifest file '/tmp/pip-pip-egg-info-a8tb73r0/psycopg2_binary.egg-info/SOURCES.txt'
2.849
2.849       Error: pg_config executable not found.
2.849
2.849       pg_config is required to build psycopg2 from source.  Please add the directory
2.849       containing pg_config to the $PATH or specify the full executable path with the
2.849       option:
2.849
2.849           python setup.py build_ext --pg-config /path/to/pg_config build ...
2.849
2.849       or with the pg_config option in 'setup.cfg'.
2.849
2.849       If you prefer to avoid building psycopg2 from source, please install the PyPI
2.849       'psycopg2-binary' package instead.
2.849
2.849       For further information please check the 'doc/src/install.rst' file (also at
2.849       <https://www.psycopg.org/docs/install.html>).
2.849
2.849       [end of output]
2.849
2.849   note: This error originates from a subprocess, and is likely not a problem with pip.
2.852 error: metadata-generation-failed
2.852
2.852 × Encountered error while generating package metadata.
2.852 ╰─> See above for output.
2.852
2.852 note: This is an issue with the package mentioned above, not pip.
2.852 hint: See above for details.
2.867
2.867 [notice] A new release of pip is available: 23.2.1 -> 23.3.1
2.867 [notice] To update, run: pip install --upgrade pip
------
failed to solve: process "/bin/sh -c python -m pip install -r requirements.txt" did not complete successfully: exit code: 1

**Comment by reuf** [comment]
I resolved the issue after adding this:

```
RUN apt-get update \
    && apt-get -y install libpq-dev gcc \
    && pip install psycopg2
```

to Dockerfile
right after

```
# Create a non-privileged user that the app will run under.
# See https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user
ARG UID=10001
RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/nonexistent" \
    --shell "/sbin/nologin" \
    --no-create-home \
    --uid "${UID}" \
    appuser
```

**Comment by craig-osterhout** [comment]
Thanks @reuf.
Are you using a Mac with an ARM processor?

**Comment by slurpyb** [comment]
I had the same issue, and advice provided by @reuf also fixed it.

Ubuntu 23.10 linux 6.5.0-14-generic

**Comment by craig-osterhout** [comment]
After looking at the error provided above, it looks like the Dockerfile is using the base image `python:3.12.0-slim`.
I was able to reproduce the error using that version.
The tutorial specifies version `3.11.4`.


If you update `ARG PYTHON_VERSION=3.12.0` to `ARG PYTHON_VERSION=3.11.4` in your Dockerfile, do you still get an error?

**Comment by craig-osterhout** [comment]
Closing as stale.
